### ISSUE TITLE
Still getting annoying update messages even though the app has been removed

### ISSUE THREAD

**Issue by oparoz** [owncloud/updater#173]
1. Switched to Daily
2. Could not update because of bug preventing us from upgrading to daily
3. Went from 8.1.3 to master
4. App isn't included in `core` and yet I still get messages telling me I should update to Daily

App list

```
Enabled:
  - activity: 2.1.3
  - files: 1.1.11
  - files_sharing: 0.6.3
  - files_texteditor: 2.0
  - files_versions: 1.0.6
  - gallery: 14.0.0
  - provisioning_api: 0.2
Disabled:
  - encryption
  - files_external
  - files_trashbin
  - user_ldap
  - user_webdavauth
```
