### ISSUE TITLE
integrity-check command shows error after running updater from 9.0.1 stable to daily stable9

### ISSUE THREAD

**Issue by davitol** [owncloud/updater#342]
### Steps to reproduce
1. Install 9.0.1. stable oC version
2. Make sure the updater downloads the daily stable9 package 
3. Run the updater
4. Run the integrity-check command

### Expected behaviour
Integrity-check command output shows no errors.

### Actual behaviour
Integrity-check command shows an error in its output

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:**version":"9.0.2.0","versionstring":"9.0.2 RC1","edition":""

**Updated from an older ownCloud or fresh install:** updated from 9.0.1 stable

### Integrity-check output
sudo -u www-data ./occ integrity:check-core

``` 
  - INVALID_HASH:
    - 3rdparty/composer/autoload_classmap.php:
      - expected: abe09be19b6d427283cbfa7c4156d2c342cd9368d7d0564828a00ae02c435b642e7092cef444f94635f370dbe507eb6b2aa05109b32d8fb5d8a65c3a5a1c658f
      - current: 4de95285a99044d62773dca1f7014a647ed8c6e08cfa587d1c8b865f49e9df776aa02c2d3b80939daf0eb0f497121757c499667938de17bbb2deb1c03f0090f0
    - 3rdparty/composer/LICENSE:
      - expected: 8e82aa3b2b27802b2c9d18fe596739e791f3d187b7d231d93baafa663da15813031e386f77a14ebd512695b061e896b7bef82e8f23e697a0761a8611d8c07b04
      - current: 90a255aa80d0e5a7c5bf84901dbd450249908434e0b4d97a7eb0d80b37ff072b2efc8bd4c57f16b618fcf46dcc8213c22baa860254bde06d9eea347ce3d592c0
    - 3rdparty/composer/installed.json:
      - expected: a4d896ff2d5f565ea51aeb57e6f16504fbf79fc40822745793808a1d8e82fbc9381091f927720a79ba0e793c71539999a1fa767d17f84d6a30e9829400ed0722
      - current: 043dd72279d7bf65b8cf755620f4db22500a5c826ad770ce18d08bfd1fe961f72550f6d73fae38c0f6c37a69553ba223316ff1b8ac798809decf212d85afb056
    - 3rdparty/composer.json:
      - expected: 7309e217188a61a6ac39a5d4cd70b1c43e86b49d1bf903d72d561aa231a1481192f73e45fe20b8f85d57e95925bb6567d382bab5aaba661b533a589dc48287e7
      - current: a6a9174f672638566a53d43a82503872795c536fbc5e4562a9a43028542c33ecb2419749a393132d00f9518f0cb0c82cc81383073d697acb615026211e0d3293
    - 3rdparty/composer.lock:
      - expected: 4009394ebef9351310157269ebfc244893b281dc40285482665a6dc27047e80ffca38f7ce912c30d95ea5b20a98bc8e0740b866d4f92211e912ba568c0e1486e
      - current: 8e82a37d2aa9b511306d51f2782c0b03f9bdc1ebd31856e576932d73cd8b9fe49b2c787a02a7ae122992c60a23dfad0e744c116b1db5622041f2498852677b4f
    - 3rdparty/sabre/dav/composer.json:
      - expected: a07fe7be4630028e2a904d1530f76f105ef299a654679ea8a5ec8dd5f76556e2c4afffe017caed32d7c6bfc4a6a1be26fcdf973e6303a2ecc00239ac39a1ec16
      - current: 075c6f3eeaa579c2c974725e89a373243452035aebd2bf7b2ebc79afef55d82ac0de54b3805ca950c0d92d7e88f715dc1487afe38815475afdbdbaa310d18c26
    - 3rdparty/sabre/dav/CHANGELOG.md:
      - expected: a00ce8728fee3d85aec04b5fcaf707cc928418d065e5fba0cfaa19017a59d1d2a583a31afa0538dc6779464c8312f32375805d9089eab234addff71053db0ee7
      - current: 1680660bf8eeba002066fa0299dd99b85052d8d5d78fe5549539160e8c71cac5e69e304232c8be824ae5a3484b7f4ec1a6e5ea39b8c4a5954d153bd94d5158ff
    - 3rdparty/sabre/dav/lib/CalDAV/Plugin.php:
      - expected: c674009a1a62b833789b9f6d30affc5306147559103655505bb88915eecd961367dcfca593a53d65a16c81f6cc3b17b578805c34e82dfeeaf25a3b1ad6aeedb6
      - current: 205b4616980dd0bb635b67cf4f54ba66f06405fc72a7b19742be5d6fed4b11517f3160101cbf326ae17010741310ab8d3ed739cf4a07ee43a055f904efc0a142
    - 3rdparty/sabre/dav/lib/DAV/Version.php:
      - expected: 197daddea9674aece439b4927c48a3a986fd16a3196be387ac825cb8350c9e5be0b1ed6567188debad27a672bf65fffe64f2051e8c206e8f9847ec24e1036793
      - current: 753a49f006305bb42c811aab2a8ea2fdd4d97e4697065e76781fdb632001b9f3776ba9223baa2fbf9cf2ad52ca00972f8ff97d1aaa8d9d894629e10dff61a617
```
